In [1]:
import json
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
sphere_sample ={
    'hydrophobic_moment': [0.6, 1.00],
    'net_charge': [0.4, 0.6],
}

fiber_sample = {
    'has_beta_sheet_content': [0.1, 1],
    'net_charge': [0.4, 0.6],
}

samples = [sphere_sample, fiber_sample]

In [3]:
min_max = {
    "has_beta_sheet_content": (0.0, 1.0),
    "hydrophobic_moment": (0.000000, 1.998000),
    "net_charge": (-6.000000, 6.000000),
    "ap":(0.959986, 2.897030)
}

for sample in samples:
    for key in sample:
        if key in ['length','sequence']:
            continue
        sample[key][0] = sample[key][0] * (min_max[key][1] - min_max[key][0]) + min_max[key][0]
        sample[key][1] = sample[key][1] * (min_max[key][1] - min_max[key][0]) + min_max[key][0]

samples

[{'hydrophobic_moment': [1.1987999999999999, 1.998],
  'net_charge': [-1.1999999999999993, 1.1999999999999993]},
 {'has_beta_sheet_content': [0.1, 1.0],
  'net_charge': [-1.1999999999999993, 1.1999999999999993]}]

In [4]:
fiber_samples = pd.read_csv('gen_peptides/fibers_metrics.csv')
fiber_samples['has_beta_sheet_content'] = (fiber_samples['beta_sheet_fraction'] > 0.1).astype(int)
fiber_samples.drop(columns=['peptide_id'], inplace=True)
fiber_samples.drop_duplicates(subset=['sequence'], inplace=True)
fiber_samples

,sequence,beta_sheet_fraction,extension_ratio,hydrophobic_moment,planarity_index,curvature_score,radius_of_gyration,alternating_pattern_score,net_charge,aromatic_interaction_score,has_beta_sheet_content
0,CIYFSICLL,0.0,0.401278,0.747778,1.622293,88.754031,4.473587,0.9085,0,1,0
1,VLCFIWN,0.0,0.450900,0.718571,1.378926,79.605695,4.366486,0.5275,0,0,0
2,FCYNPEFC,0.0,0.374525,0.227500,1.239957,78.318447,4.810864,0.9250,-1,1,0
3,LVAWVFQIW,0.0,0.401715,0.797778,1.571811,87.797882,4.494652,0.5710,0,0,0
4,VYPFLMPW,0.0,0.387029,0.660000,1.399808,85.441300,4.173064,0.1300,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
3789,IHLQCQIEW,0.0,0.280102,0.231111,0.756566,61.163858,5.681388,1.6940,-1,0,0
3790,YAYQPDCWL,0.0,0.452786,0.185556,1.525226,75.207558,5.101702,0.4780,-1,1,0
3791,FPIVYSPC,0.0,0.246856,0.532500,1.936038,72.342199,4.063038,0.4100,0,0,0
3792,VFCYCFPLW,0.0,0.532961,0.698889,1.401320,74.393543,5.442312,0.4070,0,0,0
3793,AFKINQYF,0.0,0.399376,0.188750,1.402217,87.520884,4.151700,1.0775,1,1,0

In [5]:
valid_fibers = fiber_samples.copy()

for key in fiber_sample:
    valid_fibers = valid_fibers[(valid_fibers[key] >= fiber_sample[key][0]) & ((valid_fibers[key] <= fiber_sample[key][1]))]

valid_fibers

,sequence,beta_sheet_fraction,extension_ratio,hydrophobic_moment,planarity_index,curvature_score,radius_of_gyration,alternating_pattern_score,net_charge,aromatic_interaction_score,has_beta_sheet_content
179,QCVSPHWPAP,0.500000,0.140910,0.173000,1.390015,71.191524,4.944672,0.3660,0,0,1
456,AIVFPGTFHQ,0.500000,0.126765,0.476000,0.863145,59.594237,5.372047,0.4040,0,1,1
572,CQCTAGCYVW,0.500000,0.150142,0.322000,1.274791,61.671530,5.226244,0.3840,0,0,1
621,QYWCPGMAIC,0.500000,0.132561,0.404000,0.865241,64.124233,5.293483,0.0320,0,1,1
624,PAPFPWSIWI,0.500000,0.112988,0.637000,0.808338,57.768717,5.383118,0.8780,0,0,1
732,PFAIPYCSTP,0.500000,0.169935,0.387000,1.480606,66.983398,5.002869,0.3340,0,0,1
971,LICWTGHCHH,0.500000,0.124979,0.306000,0.917254,57.007593,5.352198,0.4120,0,0,1
1072,LDIYNHPFF,0.571429,0.154160,0.346667,1.069240,65.518282,4.779394,0.5565,-1,2,1
1296,RCVQGGHPFC,0.500000,0.140804,0.015000,1.069499,65.829440,5.256677,0.1020,1,0,1
1445,AFLWNGISYQ,0.500000,0.129396,0.399000,0.865597,62.762412,5.325236,0.2180,0,1,1
1458,PVWRADSWHC,0.500000,0.128479,0.028000,0.904062,68.576399,5.191122,0.4440,0,1,1
1467,TYPFANGVIH,0.500000,0.113097,0.390000,0.963749,60.494129,5.210889,0.2400,0,1,1
1573,PFLFAGDVHM,0.500000,0.117019,0.508000,0.935784,59.683496,5.335581,0.8160,-1,0,1
1680,CVSAPGIFHC,0.500000,0.129996,0.487000,0.800032,60.836251,5.357921,0.4900,0,0,1
1686,ILSCPGWPFY,0.500000,0.148918,0.553000,0.990197,64.665088,5.175341,0.2220,0,1,1
1741,TMQYDNWSLH,0.500000,0.128799,0.039000,1.038349,64.918909,5.218322,0.1060,-1,1,1
1955,FAHHNGCVFE,0.500000,0.127238,0.253000,0.969115,58.884431,5.395301,0.0900,-1,0,1
2226,RIIAGYDVV,0.571429,0.141022,0.316667,1.107692,62.861972,4.786469,0.9330,0,0,1
2365,RAVYGDFVFL,0.500000,0.131214,0.353000,1.075478,66.903890,5.174422,0.1420,0,1,1
2369,QIRTYDFLVF,0.500000,0.135199,0.183000,0.783171,64.620072,5.266136,0.7060,0,0,1
2427,VFLVPVDFKY,0.500000,0.165650,0.466000,1.002599,66.197768,5.292956,0.9880,0,2,1
2515,ILSFPDKVTY,0.500000,0.150334,0.246000,0.792993,60.032913,5.356304,0.5840,0,0,1
2671,FTFIPGWVDL,0.500000,0.134759,0.636000,1.038112,61.879496,5.299164,0.3080,-1,0,1
3078,VVVDNQWSFK,0.500000,0.110872,0.103000,0.772587,59.881723,5.353353,1.1460,0,0,1
3148,PVFCADQWFC,0.500000,0.123741,0.384000,0.834698,63.921420,5.257142,0.1400,-1,2,1
3406,LFLTADSYCF,0.500000,0.136836,0.454000,0.877450,66.279162,5.249480,0.2320,-1,0,1
3497,HYVSGRFLIY,0.500000,0.148210,0.260000,1.224018,61.633633,5.294067,0.9720,1,1,1
3564,PALMPGETWY,0.500000,0.130540,0.332000,0.967906,63.833289,5.268240,0.1160,-1,1,1
3594,ALVDDKYFFI,0.500000,0.139468,0.348000,0.977714,67.569179,5.202222,0.2040,-1,2,1

In [6]:
peptide_propensities_fibers = pd.read_csv('./gen_peptides/filtered_ap_peptides_fiber.txt', names=['sequence', 'sequence_3', 'ap', 'assembly'])
peptide_propensities_fibers['ap'] = min_max['ap'][0] + (peptide_propensities_fibers['ap'] * (min_max['ap'][1] - min_max['ap'][0]))
peptide_propensities_fibers

        sequence                                sequence_3        ap  assembly
0       ALWYVFPE           Ala-Leu-Trp-Tyr-Val-Phe-Pro-Glu  1.880959  0.997710
1      AVRADYVYC       Ala-Val-Arg-Ala-Asp-Tyr-Val-Tyr-Cys  1.870947  0.998530
2     VPVFLPEAIF   Val-Pro-Val-Phe-Leu-Pro-Glu-Ala-Ile-Phe  1.958868  0.999817
3     PVFDGTALHC   Pro-Val-Phe-Asp-Gly-Thr-Ala-Leu-His-Cys  1.795246  0.977304
4      KGFSYEQYC       Lys-Gly-Phe-Ser-Tyr-Glu-Gln-Tyr-Cys  1.835776  0.991674
...          ...                                       ...       ...       ...
3789   RVCNYVAFW       Arg-Val-Cys-Asn-Tyr-Val-Ala-Phe-Trp  1.941425  0.999832
3790     LGCFQKY               Leu-Gly-Cys-Phe-Gln-Lys-Tyr  1.866403  0.986392
3791    KYFEAGFH           Lys-Tyr-Phe-Glu-Ala-Gly-Phe-His  1.866125  0.997916
3792  NASSLQPWVW   Asn-Ala-Ser-Ser-Leu-Gln-Pro-Trp-Val-Trp  1.869704  0.998846
3793  FPVIIVVVPV   Phe-Pro-Val-Ile-Ile-Val-Val-Val-Pro-Val  2.052931  0.999889

[3794 rows x 4 columns]

In [7]:
merged_valid_fibers = valid_fibers.merge(peptide_propensities_fibers, on='sequence', how='inner')
merged_valid_fibers.sort_values(by='ap', ascending=False)[['sequence', 'sequence_3', 'ap']][:15]

      sequence                                sequence_3        ap
20  VFLVPVDFKY   Val-Phe-Leu-Val-Pro-Val-Asp-Phe-Lys-Tyr  2.078700
4   PAPFPWSIWI   Pro-Ala-Pro-Phe-Pro-Trp-Ser-Ile-Trp-Ile  2.056355
14  ILSCPGWPFY   Ile-Leu-Ser-Cys-Pro-Gly-Trp-Pro-Phe-Tyr  2.025387
5   PFAIPYCSTP   Pro-Phe-Ala-Ile-Pro-Tyr-Cys-Ser-Thr-Pro  2.024292
22  FTFIPGWVDL   Phe-Thr-Phe-Ile-Pro-Gly-Trp-Val-Asp-Leu  1.984914
21  ILSFPDKVTY   Ile-Leu-Ser-Phe-Pro-Asp-Lys-Val-Thr-Tyr  1.953139
26  HYVSGRFLIY   His-Tyr-Val-Ser-Gly-Arg-Phe-Leu-Ile-Tyr  1.940580
13  CVSAPGIFHC   Cys-Val-Ser-Ala-Pro-Gly-Ile-Phe-His-Cys  1.933979
24  PVFCADQWFC   Pro-Val-Phe-Cys-Ala-Asp-Gln-Trp-Phe-Cys  1.926734
10  PVWRADSWHC   Pro-Val-Trp-Arg-Ala-Asp-Ser-Trp-His-Cys  1.926473
7    LDIYNHPFF       Leu-Asp-Ile-Tyr-Asn-His-Pro-Phe-Phe  1.926025
19  QIRTYDFLVF   Gln-Ile-Arg-Thr-Tyr-Asp-Phe-Leu-Val-Phe  1.909036
18  RAVYGDFVFL   Arg-Ala-Val-Tyr-Gly-Asp-Phe-Val-Phe-Leu  1.908686
25  LFLTADSYCF   Leu-Phe-Leu-Thr-Ala-Asp-Ser-Tyr-Cys-Phe  1.898056
6   LICWTGHCHH   Leu-Ile-Cys-Trp-Thr-Gly-His-Cys-His-His  1.893718

In [12]:
sphere_samples = pd.read_csv('gen_peptides/spheres_metrics.csv')
sphere_extra_samples = pd.read_csv('gen_peptides/spheres_metrics_extra.csv')
sphere_samples = pd.concat([sphere_samples, sphere_extra_samples], ignore_index=True)
sphere_samples.drop(columns=['peptide_id'], inplace=True)
sphere_samples.drop_duplicates(subset=['sequence'], inplace=True)
sphere_samples

,sequence,beta_sheet_fraction,extension_ratio,hydrophobic_moment,planarity_index,curvature_score,radius_of_gyration,alternating_pattern_score,net_charge,aromatic_interaction_score
0,LLYPGYI,0.0,0.221467,0.660000,1.612789,76.109668,3.567114,0.315000,0,1.0
1,FFIMM,0.0,0.398617,1.008000,1.391486,87.024219,3.097588,0.155000,0,1.0
2,PWLCE,0.0,0.398615,0.308000,1.391539,87.020234,3.097735,0.403333,-1,0.0
3,VFAMY,0.0,0.398600,0.758000,1.391667,87.023910,3.097622,0.261667,0,1.0
4,LYEPIV,0.0,0.454657,0.526667,1.607155,82.084048,3.542254,0.080000,-1,0.0
...,...,...,...,...,...,...,...,...,...,...
4168,VLDFW,0.0,NaN,0.648000,NaN,NaN,NaN,NaN,-1,NaN
4169,FYGYFIV,0.0,NaN,0.834286,NaN,NaN,NaN,NaN,0,NaN
4170,VLFII,0.0,NaN,1.218000,NaN,NaN,NaN,NaN,0,NaN
4171,CYFGW,0.0,NaN,0.606000,NaN,NaN,NaN,NaN,0,NaN
4172,LFLVIFI,0.0,NaN,1.191429,NaN,NaN,NaN,NaN,0,NaN

In [13]:
valid_spheres = sphere_samples.copy()

for key in sphere_sample:
    valid_spheres = valid_spheres[(valid_spheres[key] >= sphere_sample[key][0]) & ((valid_spheres[key] <= sphere_sample[key][1]))]

valid_spheres

,sequence,beta_sheet_fraction,extension_ratio,hydrophobic_moment,planarity_index,curvature_score,radius_of_gyration,alternating_pattern_score,net_charge,aromatic_interaction_score
20,IFFFII,0.0,0.454611,1.285000,1.451293,87.059164,3.445264,0.063333,0,2.0
111,IFLFIFV,0.0,0.437745,1.210000,1.481132,87.039522,3.791915,0.035000,0,0.0
152,FFIFFI,0.0,0.452924,1.253333,1.399537,89.456775,3.392132,0.000000,0,5.0
281,FLFIII,0.0,0.451873,1.263333,1.434598,89.172317,3.418710,0.020000,0,1.0
302,IWIFIII,0.0,0.606355,1.271429,0.611429,69.515868,5.312401,0.253333,0,0.0
...,...,...,...,...,...,...,...,...,...,...
3888,ILLFIF,0.0,NaN,1.210000,NaN,NaN,NaN,NaN,0,NaN
3928,FFFIFF,0.0,NaN,1.221667,NaN,NaN,NaN,NaN,0,NaN
4104,FFIFLF,0.0,NaN,1.200000,NaN,NaN,NaN,NaN,0,NaN
4125,LIFIF,0.0,NaN,1.240000,NaN,NaN,NaN,NaN,0,NaN
4170,VLFII,0.0,NaN,1.218000,NaN,NaN,NaN,NaN,0,NaN

In [14]:
peptide_propensities_spheres = pd.read_csv('./gen_peptides/filtered_ap_peptides_spheres.txt', names=['sequence', 'sequence_3', 'ap', 'assembly'])
peptide_propensities_spheres_extra = pd.read_csv('./gen_peptides/filtered_ap_peptides_spheres_extra.txt', names=['sequence', 'sequence_3', 'ap', 'assembly'])
peptide_propensities_spheres = pd.concat([peptide_propensities_spheres, peptide_propensities_spheres_extra], ignore_index=True)
peptide_propensities_spheres['ap'] = min_max['ap'][0] + (peptide_propensities_spheres['ap'] * (min_max['ap'][1] - min_max['ap'][0]))
peptide_propensities_spheres

     sequence                    sequence_3        ap   assembly
0       FVCIT           Phe-Val-Cys-Ile-Thr  2.196335   0.999973
1       CYTEW           Cys-Tyr-Thr-Glu-Trp  1.929523   0.999701
2      QLYQVL       Gln-Leu-Tyr-Gln-Val-Leu  1.879860   0.983154
3       IPLMV           Ile-Pro-Leu-Met-Val  2.053032   0.998857
4       WAIFF           Trp-Ala-Ile-Phe-Phe  2.256845   1.000000
...       ...                           ...       ...        ...
5021   IFFWFF       Ile-Phe-Phe-Trp-Phe-Phe  2.222983  18.216171
5022   MFVIMI       Met-Phe-Val-Ile-Met-Ile  2.028435   7.655947
5023  FVMLFMY   Phe-Val-Met-Leu-Phe-Met-Tyr  2.189521  13.019874
5024  FMIVYAP   Phe-Met-Ile-Val-Tyr-Ala-Pro  2.102146   8.344761
5025   FWVWIW       Phe-Trp-Val-Trp-Ile-Trp  2.142309  14.451995

[5026 rows x 4 columns]

In [15]:
merged_valid_spheres = valid_spheres.merge(peptide_propensities_spheres, on='sequence', how='inner')
merged_valid_spheres.sort_values(by='ap', ascending=False)[['sequence', 'sequence_3', 'ap']][:15]

   sequence                sequence_3        ap
66    FLFFI       Phe-Leu-Phe-Phe-Ile  2.340770
68    LFFIF       Leu-Phe-Phe-Ile-Phe  2.316783
10    FVIFF       Phe-Val-Ile-Phe-Phe  2.300558
74    LIFIF       Leu-Ile-Phe-Ile-Phe  2.292805
34    FIVFF       Phe-Ile-Val-Phe-Phe  2.290336
67    IWIIF       Ile-Trp-Ile-Ile-Phe  2.286610
65   FLIFFF   Phe-Leu-Ile-Phe-Phe-Phe  2.284504
9     LVIIF       Leu-Val-Ile-Ile-Phe  2.280685
70    WVIII       Trp-Val-Ile-Ile-Ile  2.280227
47    FIFVF       Phe-Ile-Phe-Val-Phe  2.271703
58    FIFIF       Phe-Ile-Phe-Ile-Phe  2.264918
40    FFLFI       Phe-Phe-Leu-Phe-Ile  2.263951
28    LIIVF       Leu-Ile-Ile-Val-Phe  2.258977
73   FFIFLF   Phe-Phe-Ile-Phe-Leu-Phe  2.258782
8    FLIFFI   Phe-Leu-Ile-Phe-Phe-Ile  2.249841

In [16]:
merged_valid_spheres.to_csv('valid_spheres_new.csv', index=False)
merged_valid_fibers.to_csv('valid_fibers_new.csv', index=False)